version: '3.7'
services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - db

    db:
        image: postgres:12.2
        environment:
            - POSTGRES_DB=tasting_db
            - POSTGRES_PASSWORD=mysecretpassword
        ports:
            - 5432:5432
