name: CI pipeline

on: [push]

jobs:
    build:
        name: Feature tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Start the test environment
              run: ./start.sh --detach

            -   name: Wait 20 sec
                uses: jakejarvis/wait-action@master
                with:
                    time: '20s'

            - name: Run feature tests
              run: ./test.sh
